import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Ehsan',
      email: 'admin@wfc.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Abdullah',
      email: 'user@wfc.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Surmai King Mackerel',
      slug: 'surmai-king-mackerel',
      category: 'Big Fish',
      image: '/images/p1.png',
      countInStock: 10,
      brand: 'wfc',
      rating: 1.5,
      numReviews: 2,
      description: 'soft white meat max yield',
      price: 1000,
    },
    {
      // _id: '2',
      name: 'Hera Red Snapper',
      slug: 'hera-red-snapper',
      category: 'Medium Fish',
      image: '/images/p2.png',
      countInStock: 10,
      brand: 'wfc',
      rating: 2.5,
      numReviews: 4,
      description: 'soft white meat max yield',
      price: 700,
    },
    {
      // _id: '3',
      name: 'Dhotar Grunter Javelin',
      slug: 'dhotar-grunter-javelin',
      category: 'Medium Fish',
      image: '/images/p3.png',
      countInStock: 10,
      brand: 'wfc',
      rating: 3,
      numReviews: 6,
      description: 'soft white meat max yield',
      price: 700,
    },
    {
      // _id: '4',
      name: 'Ghisser Grouper',
      slug: 'ghisser-grouper',
      category: 'Big Fish',
      image: '/images/p4.png',
      countInStock: 10,
      brand: 'wfc',
      rating: 2,
      numReviews: 10,
      description: 'soft white meat max yield',
      price: 800,
    },
    {
      // _id: '5',
      name: 'Mushka Croaker',
      slug: 'mushka-croaker',
      category: 'Small Fish',
      image: '/images/p5.png',
      countInStock: 0,
      brand: 'wfc',
      rating: 5,
      numReviews: 15,
      description: 'soft white meat max yield',
      price: 500,
    },
    {
      // _id: '6',
      name: 'Dhandia Sea Bream',
      slug: 'dhandia-sea-bream',
      category: 'Small Fish',
      image: '/images/p6.png',
      countInStock: 10,
      brand: 'wfc',
      rating: 0,
      numReviews: 23,
      description: 'soft white meat max yield',
      price: 500,
    },
  ],
};

export default data;
