const data = {
  products: [
    {
      name: 'Surmai King Mackerel',
      slug: 'surmai-king-mackerel',
      category: 'Big Fish',
      image: '/images/p1.png',
      countInStock: 10,
      brand: 'wfc',
      rating: 4.5,
      numReviews: 10,
      description: 'soft white meat max yield',
      price: 1000,
    },
    {
      name: 'Hera Red Snapper',
      slug: 'hera-red-snapper',
      category: 'Medium Fish',
      image: '/images/p2.png',
      countInStock: 10,
      brand: 'wfc',
      rating: 4.5,
      numReviews: 10,
      description: 'soft white meat max yield',
      price: 700,
    },
    {
      name: 'Dhotar Grunter Javelin',
      slug: 'dhotar-grunter-javelin',
      category: 'Medium Fish',
      image: '/images/p3.png',
      countInStock: 10,
      brand: 'wfc',
      rating: 4.5,
      numReviews: 10,
      description: 'soft white meat max yield',
      price: 700,
    },
    {
      name: 'Ghisser Grouper',
      slug: 'ghisser-grouper',
      category: 'Big Fish',
      image: '/images/p4.png',
      countInStock: 10,
      brand: 'wfc',
      rating: 4.5,
      numReviews: 10,
      description: 'soft white meat max yield',
      price: 800,
    },
    {
      name: 'Mushka Croaker',
      slug: 'mushka-croaker',
      category: 'Small Fish',
      image: '/images/p5.png',
      countInStock: 10,
      brand: 'wfc',
      rating: 4.5,
      numReviews: 10,
      description: 'soft white meat max yield',
      price: 500,
    },
  ],
};

export default data;
